### ISSUE TITLE
KeyError: '_type'

### ISSUE THREAD

**Issue by BrianCrowe3** [owdevel/ytdl-nfo#20]
I'd like to preface this by stating I have limited programming experience, and absolutely no experience with python. That being said, it might not be any surprise that I cant get this program working for the life of me. I've tried multiple different .json files on both Windows 10 and a 100% fresh Ubuntu install.

Here's the terminal print out from ubuntu, Windows 10 prints out basically the same thing:

jim@jim-virtual-machine:~/Downloads/a$ ytdl-nfo test.json
Processing test.json with file specific extractor
Traceback (most recent call last):
  File "/home/jim/.local/bin/ytdl-nfo", line 8, in <module>
    sys.exit(main())
  File "/home/jim/.local/pipx/venvs/ytdl-nfo/lib/python3.10/site-packages/ytdl_nfo/__init__.py", line 27, in main
    file.process()
  File "/home/jim/.local/pipx/venvs/ytdl-nfo/lib/python3.10/site-packages/ytdl_nfo/Ytdl_nfo.py", line 27, in process
    if self.data['_type'] != "video":
KeyError: '_type'

Here's the command I used to acquire the .json file above, in case that helps:
youtube-dl --write-info-json --skip-download https://www.youtube.com/watch?v=tPEE9ZwTmy0
(youtube-dl installed with pipx)

I really like the idea of a program like this, I'm willing to do whatever is within my power to get it working. Hopefully I'm just doing something wrong.

**Comment by pineapplemachine** [comment]
This is happening because the JSON you are trying to read does not fit the format that ytdl-nfo expects. I am not sure why this would be the case. Normally, it would be because you are using a JSON file not actually produced by youtube-dl. Can you please upload one or more of the JSON files directly that you tried to process using ytdl-nfo? This would help us to help you. Please also let us know the complete file names of these JSON files.

There was a bug with the program here, though, which your issue revealed. This bug was causing you to get this unclear and complicated "Traceback" error message that you shared, instead of the intended error message which would have more clearly informed you that the input _is not a video metadata file_. Thank you for reporting this! In the future, the program should give a more helpful message in this case.

**Comment by BrianCrowe3** [comment]
@pineapplemachine here's links to two json files I've tested as not working:
https://www.dropbox.com/s/2cjw7vj9w912lg0/Shortest%20Video%20on%20Youtube-tPEE9ZwTmy0.info.zip?dl=1
https://www.dropbox.com/s/w006xw5g3dsy07s/Morrowind%20Any%25%20speedrun%20in%202_47%20IGT-e7H3L0S6M6w.info.zip?dl=1

Full filenames: 
Shortest Video on Youtube-tPEE9ZwTmy0.info.json
Morrowind Any% speedrun in 2_47 IGT-e7H3L0S6M6w.info.json

The exact commands I used to download them:
youtube-dl --write-info-json --skip-download https://www.youtube.com/watch?v=tPEE9ZwTmy0
youtube-dl --write-info-json --skip-download https://www.youtube.com/watch?v=e7H3L0S6M6w

The only things I can think of is either YouTube changed something(maybe region specific?), or there's a problem with the youtube-dl version I'm using. I don't know which version pipx installs, but the version I was using on Windows 10 was youtube-dl 2021.12.17 downloaded directly from their github.

Also I'm glad I inadvertently revealed a different bug lol, happy to help.

**Comment by pineapplemachine** [comment]
@owdevel I was able to reproduce this issue with youtube-dl. It looks like @BrianCrowe3 did everything right, and it so happens that the most recent release of youtube-dl actually does not write a ` _type` key to the info JSON. It might be good to remove that check entirely?

@BrianCrowe3 In the meantime, until this is fixed, I suggest using the tool yt-dlp instead. This is a more up-to-date alternate version of youtube-dl. You should be able to use it the same way you've used youtube-dl. The JSON files that yt-dlp writes ought to be handled correctly by ytdl-nfo.

The yt-dlp github page is here: https://github.com/yt-dlp/yt-dlp

The version of yt-dlp that I have installed and made sure includes this JSON key is 2022.09.01. It is possible that a more recent version may produce the same issue as you encountered with the most recent youtube-dl, though this would surprise me.

**Comment by BrianCrowe3** [comment]
@pineapplemachine latest version of yt-dlp works great, thanks!

**Comment by owdevel** [comment]
> @owdevel I was able to reproduce this issue with youtube-dl. It looks like @BrianCrowe3 did everything right, and it so happens that the most recent release of youtube-dl actually does not write a ` _type` key to the info JSON. It might be good to remove that check entirely?

Just reproduced it myself and I agree with your analysis. Best remove the check for now at least. I believe it was added to ensure playlist .info.json files don't get processed, but that is a small issue compared to breaking compatibility.

Thank you for bringing up the issue.
