### ISSUE TITLE
No module named 'pkg_resources' when using pipx

### ISSUE THREAD

**Issue by xdevs23** [owdevel/ytdl-nfo#30]
I ran `pipx install ytdl-nfo`, output:

```
  installed package ytdl-nfo 0.3.0, installed using Python 3.12.3
  These apps are now globally available
    - ytdl-nfo
done! ✨ 🌟 ✨
```

Then I ran `ytdl-nfo`, but I get an error:

```
Traceback (most recent call last):
  File "/home/simao/.local/bin/ytdl-nfo", line 5, in <module>
    from ytdl_nfo import main
  File "/home/simao/.local/share/pipx/venvs/ytdl-nfo/lib/python3.12/site-packages/ytdl_nfo/__init__.py", line 4, in <module>
    from .Ytdl_nfo import Ytdl_nfo
  File "/home/simao/.local/share/pipx/venvs/ytdl-nfo/lib/python3.12/site-packages/ytdl_nfo/Ytdl_nfo.py", line 3, in <module>
    from .nfo import get_config
  File "/home/simao/.local/share/pipx/venvs/ytdl-nfo/lib/python3.12/site-packages/ytdl_nfo/nfo.py", line 5, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

Python version: Python 3.12.3
OS: Arch Linux x86_64
Kernel: Linux 6.9.4-nitrous-1
Shell: zsh 5.9
CPU: AMD Ryzen 9 3900X (24) @ 4.67 GHz
Locale: en_US.UTF-8

**Comment by pineapplemachine** [comment]
It looks as though this may be an issue with your Python environment, rather than with ytdl-nfo.

> This error message is caused by a missing/broken Python `setuptools` package. 

https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources

**Comment by 3ThumbsUp** [comment]
Did you manage to resolve this? I'm also on Arch Linux and getting the same error, but installing the setuptools package doesn't seem to help (I've tried both through the Arch repositories and through pipx).

**Comment by xdevs23** [comment]
> Did you manage to resolve this? I'm also on Arch Linux and getting the same error, but installing the setuptools package doesn't seem to help (I've tried both through the Arch repositories and through pipx).

Unfortunately, I have not. Setuptools is installed:

```
$ pacman -Q python-setuptools
python-setuptools 1:69.0.3-6
```

I installed ytdl-nfo using pipx.

**Comment by Morikko** [comment]
> [gh-95299](https://github.com/python/cpython/issues/95299): Do not pre-install setuptools in virtual environments created with [venv](https://docs.python.org/3/library/venv.html#module-venv). This means that distutils, setuptools, pkg_resources, and easy_install will no longer available by default; to access these run pip install setuptools in the [activated](https://docs.python.org/3/library/venv.html#venv-explanation) virtual environment.

https://docs.python.org/3/whatsnew/3.12.html

It is deprecated in 3.12. You may try to manually inject `setuptools` in the pipx env or you should use a lower python version. 

For ytdl-nfo to work with python 3.12 natively, the dependency `setuptools` must be added to poetry.

**Comment by pineapplemachine** [comment]
@Morikko Thank you for suggesting that fix!

I made the change here:

https://github.com/owdevel/ytdl-nfo/pull/31

https://github.com/pineapplemachine/ytdl-nfo/tree/fix-poetry-2024-07-08

I don't have a ton of time to update my own Python install and test locally at the moment, but if someone were to follow the "Package from source" instructions in the repo's readme with that branch pulled, hopefully the issue will be resolved? (Please report back, if you do)

**Comment by breakid** [comment]
I encountered this bug, didn't think to check the Issues page, independently arrived at the same solution, and can confirm installing `setuptools` fixes the issue.

**Comment by azhai** [comment]
for pipx
```
pip install setuptools wheel      #Make sure the setuptools is installed
pipx inject ytdl-nfo setuptools   #Copy the packages to "site-packages" of pipx
```
See [ModuleNotFoundError: No module named 'pkg_resources'](https://github.com/3b1b/manim/issues/2127#issuecomment-2237924379)
